export const CHANGE_COLUMN_ORDER = 'CHANGE_COLUMN_ORDER'
// export const RESET_COLUMN_ORDER = 'RESET_COLUMN_ORDER'
export const TOGGLE_CREATE_CONTACT = 'TOGGLE_CREATE_CONTACT'
export const TOGGLE_SIDEBAR = 'SIDEBARHANDLER';